! This file is part of xtb.
!
! GFN1-fast 2.0.0: first-order electronic response kernel for the
! semi-analytic/analytic Hessian path.
!
! The routines in this module do not alter the production numerical Hessian.
! They provide the exact first-order closed-shell density response of the
! generalized eigenvalue problem
!
!     H C = S C eps,        C^T S C = I
!
! for a supplied pair of first derivatives dH and dS.  The response is the
! basic electronic building block required for a coupled SCC Hessian.  A
! separate routine maps dP and dS to the shell-resolved Mulliken charge
! response used by GFN1-xTB.
module xtb_xtb_response
   use xtb_mctc_accuracy, only : wp
   implicit none
   private

   public :: density_response_closed_shell
   public :: shell_charge_response

contains

!> Closed-shell first-order AO density response for a generalized symmetric
!> eigenvalue problem.  The occupied space is assumed to consist of the first
!> nocc eigenvectors and to carry occupation 2.0.  No approximation or
!> denominator regularisation is used: if an occupied--virtual gap is smaller
!> than gap_tol, ok is returned false so callers can fall back to the numerical
!> Hessian path.
subroutine density_response_closed_shell(C, eps, nocc, dH, dS, dP, ok, gap_tol)
   real(wp), intent(in) :: C(:, :)
   real(wp), intent(in) :: eps(:)
   integer, intent(in) :: nocc
   real(wp), intent(in) :: dH(:, :)
   real(wp), intent(in) :: dS(:, :)
   real(wp), intent(out) :: dP(:, :)
   logical, intent(out) :: ok
   real(wp), intent(in), optional :: gap_tol

   integer :: nao, nvir, i, a
   real(wp) :: denom, tol
   real(wp), allocatable :: dh_cocc(:, :), ds_cocc(:, :)
   real(wp), allocatable :: hco(:, :), sco(:, :), uvo(:, :)
   real(wp), allocatable :: xvo(:, :), yoo(:, :), soo(:, :)

   nao = size(C, 1)
   dP = 0.0_wp
   ok = .false.

   if (size(C, 2) /= nao) return
   if (size(eps) < nao) return
   if (size(dH, 1) /= nao .or. size(dH, 2) /= nao) return
   if (size(dS, 1) /= nao .or. size(dS, 2) /= nao) return
   if (size(dP, 1) /= nao .or. size(dP, 2) /= nao) return
   if (nocc < 0 .or. nocc > nao) return

   if (present(gap_tol)) then
      tol = max(0.0_wp, gap_tol)
   else
      tol = 100.0_wp*epsilon(1.0_wp)
   end if

   if (nocc == 0) then
      ok = .true.
      return
   end if

   nvir = nao - nocc

   allocate(dh_cocc(nao, nocc), ds_cocc(nao, nocc))
   allocate(hco(nao, nocc), sco(nao, nocc))
   allocate(soo(nocc, nocc), yoo(nao, nocc))

   ! Only C^T dH C_occ and C^T dS C_occ are required.  Avoid constructing
   ! full MO-basis derivative matrices because Hessian response is repeated
   ! for every nuclear Cartesian coordinate.
   dh_cocc = matmul(dH, C(:, 1:nocc))
   ds_cocc = matmul(dS, C(:, 1:nocc))
   hco = matmul(transpose(C), dh_cocc)
   sco = matmul(transpose(C), ds_cocc)
   soo = sco(1:nocc, 1:nocc)

   if (nvir > 0) then
      allocate(uvo(nvir, nocc), xvo(nao, nocc))
      do i = 1, nocc
         do a = 1, nvir
            denom = eps(i) - eps(nocc + a)
            if (abs(denom) <= tol) then
               dP = 0.0_wp
               return
            end if
            uvo(a, i) = (hco(nocc + a, i) - eps(i)*sco(nocc + a, i))/denom
         end do
      end do

      ! Orbital-relaxation part: 2*(C_v U_vo C_o^T + transpose).
      xvo = matmul(C(:, nocc+1:nao), uvo)
      dP = 2.0_wp*(matmul(xvo, transpose(C(:, 1:nocc))) &
         & + matmul(C(:, 1:nocc), transpose(xvo)))
   end if

   ! Metric response from d(C^T S C)=0.  Choosing the symmetric occupied-
   ! occupied gauge U_oo=-1/2 S^x_oo gives the gauge-invariant projector
   ! contribution -2*C_occ*S^x_oo*C_occ^T.
   yoo = matmul(C(:, 1:nocc), soo)
   dP = dP - 2.0_wp*matmul(yoo, transpose(C(:, 1:nocc)))

   ! Suppress only the insignificant antisymmetric roundoff generated by
   ! independent matrix products.  This is mathematically identical to the
   ! symmetric density response.
   dP = 0.5_wp*(dP + transpose(dP))
   ok = .true.

end subroutine density_response_closed_shell


!> First-order shell-resolved Mulliken *charge* response.
!>
!> GFN1 stores q_sh = z_sh - population_sh.  Therefore
!>
!>   dq_sh = - d population_sh
!>         = - Mulliken(dP*S + P*dS).
!>
!> The accumulation order mirrors mpopsh in scc_core.f90 so this routine can
!> later be inserted into the coupled SCC response without changing the
!> population convention.
subroutine shell_charge_response(ao2sh, S, P, dS, dP, dqsh)
   integer, intent(in) :: ao2sh(:)
   real(wp), intent(in) :: S(:, :)
   real(wp), intent(in) :: P(:, :)
   real(wp), intent(in) :: dS(:, :)
   real(wp), intent(in) :: dP(:, :)
   real(wp), intent(out) :: dqsh(:)

   integer :: nao, i, j, ish, jsh
   real(wp) :: dps

   nao = size(ao2sh)
   dqsh = 0.0_wp

   do i = 1, nao
      ish = ao2sh(i)
      do j = 1, i-1
         jsh = ao2sh(j)
         dps = dP(j,i)*S(j,i) + P(j,i)*dS(j,i)
         dqsh(ish) = dqsh(ish) - dps
         dqsh(jsh) = dqsh(jsh) - dps
      end do
      dps = dP(i,i)*S(i,i) + P(i,i)*dS(i,i)
      dqsh(ish) = dqsh(ish) - dps
   end do

end subroutine shell_charge_response

end module xtb_xtb_response
